service: wupark-backend-pi-to-image-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: prod
  environment:
    TABLE_NAME: Wupark-Pi-Image-Table
  apiGateway:
    apiKeys:
      - name: wupark-PiDb-api-key
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:us-east-1:833100170434:table/Wupark-Pi-Image-Table

functions:
  wupark_images:
    handler: handler.handler
    events:
      - http:
          path: wupark/image
          method: post
          private: true
          cors: true
     

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

resources: ${file(./config/sls.resources.yml)}