Resources:
  WuparkItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Wupark-Pi-Image-Table
      AttributeDefinitions:
        - AttributeName: lotNum
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: status
          AttributeType: N
        - AttributeName: image
          AttributeType: B
      KeySchema:
        - AttributeName: lotNum
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
        - AttributeName: status
          KeyType: RANGE
        - AttributeName: image
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST