WuparkItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WuparkItemsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
      Policies:
        - PolicyName: SecretsManager
          PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
               - dynamodb:Scan
               - dynamodb:GetItem
               - dynamodb:PutItem
               - dynamodb:UpdateItem
               - dynamodb:DeleteItem
              Resource:
                - 'arn:aws:dynamodb:us-east-1:833100170434:table/WuparkItemsTable'